package com.pbkk.KitchenService.controller;

import java.util.List;
import java.util.Map;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.pbkk.KitchenService.Repository.FoodRepository;
import com.pbkk.KitchenService.Repository.KitchenRepository;
import com.pbkk.KitchenService.model.*;
import com.pbkk.KitchenServiceUtil.*;

@RestController
@RequestMapping("/Kitchen/Food")

public class FoodController {

	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private FoodRepository foodRepository;

	@ResponseBody
	@RequestMapping("")
	public Iterable<FoodModel> test() {
		return foodRepository.findAll();
		//return foodService.getAll();
//		return Util.getSuccessResult(kitchenService.getAll())
	}
	
	@ResponseBody
	@RequestMapping("/{id}")
	public Optional<FoodModel> getKitchen(@PathVariable("id") Integer id) {
		//return foodService.getFoodbyID(id);
		return foodRepository.findById(id);
	}
	
	@ResponseBody
	@RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
	public Map<String, Object> deleteStatus(
			@PathVariable("id") Integer id) {
		   
	    //foodService.deleteFood(id_status);
		foodRepository.deleteById(id);
	    return Util.getSuccessResult();
	}
	
	@ResponseBody
	@RequestMapping(value = "/createFood", method = RequestMethod.POST)
	public Map<String, Object> createFood(			
			@RequestParam(value = "id_makanan") Integer id
			) {
		
		//foodService.createFood(name, Cost, restaurant_Id, status);
		FoodModel f = new FoodModel();
		f.setId_makanan(id);
		f.setStatus(false);
		foodRepository.save(f);
		return Util.getSuccessResult();
	}
	
	@ResponseBody
	@RequestMapping(value = "/update", method = RequestMethod.PUT)
	public Map<String, Object> updateFoodName(
			@RequestParam(value = "id_fstatus") Integer id,
			@RequestParam(value = "status") Boolean status
			) {
		FoodModel k = foodRepository.findById(id).get();
		k.setStatus(status);
		foodRepository.save(k);
		
		//foodService.updateFoodName(id_food, foodName);		
		return Util.getSuccessResult();
	}
	
}
